spring:
  application:
    name: TimeStampApp
  datasource:
    url: jdbc:mysql://localhost:3306/timestampdb?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: timestamp
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql
      mode: never 